-- 0029_operator_api_tokens.sql
--
-- Step 2 of the console-login-state-mismatch fix (see
-- .planning/debug/resolved/console-login-state-mismatch.md). Step 1 (dec6eb5,
-- PR #297) stopped `/auth/callback` writing the Zitadel access and refresh
-- tokens into the session cookie: with them included the encrypted payload
-- routinely exceeded the browser's hard 4096-byte per-cookie limit, so Chrome
-- silently discarded `tx_session` and every login looped back through
-- `/auth/login` forever. That fix bought correctness by returning
-- `getPlatformApiToken()` to null — the tokens had nowhere left to live. This
-- table is where they live now.
--
-- Why not the cookie: the math does not work and never will. A cookie holds
-- identity plus a handful of short claims comfortably; it cannot also hold an
-- OAuth access token, a refresh token, and their expiries without risking the
-- same 4096-byte cliff that caused the outage. The fix has to remove the
-- tokens from the cookie, not just shrink them.
--
-- Why a table and not Redis: ADR-003 D2a says do not add infrastructure this
-- estate cannot afford, but that argument does not reach this case — the
-- console already holds a connection to this Postgres for everything else it
-- persists, so a table costs nothing Redis would have to justify. The access
-- pattern is a point lookup by `sid` on the platform-API path, which Postgres
-- serves without difficulty at console traffic volumes.
--
-- Why identity stays in the cookie while only the tokens move: `middleware.ts`
-- runs on every request — every asset, every navigation — and has to stay
-- zero-I/O to do that without adding a database round trip to the console's
-- critical path. The cookie keeps the session claims middleware already
-- decodes locally (sub, roles, expiry) and gains one new claim, `sid`, that
-- names the row here. Only code that actually calls the platform API reads
-- this table, and only then does a lookup happen.
BEGIN;

-- =======================================================================
-- operator_api_tokens
--
-- One row per session that has authenticated against the platform API.
-- Keyed by `sid`, the random session identifier minted into the cookie
-- alongside the existing session claims — not the Zitadel `sub`, because one
-- operator can hold more than one live session (multiple browsers, tabs
-- surviving a re-login) and each needs its own token pair to refresh
-- independently.
-- =======================================================================
CREATE TABLE operator_api_tokens (
  -- The session identifier minted into the `tx_session` cookie's `sid` claim.
  -- text, not uuid, for the reason migrations 0003, 0017 and 0018 all record:
  -- a foreign-issued identifier stored as uuid fails the implicit cast and
  -- lies about its shape. `sid` is generated by this application, but it is
  -- kept text to match every other identifier this table touches and to
  -- avoid re-deriving that argument later.
  sid text PRIMARY KEY,

  -- The Zitadel `sub` this session belongs to. Not part of the primary key —
  -- `sid` alone identifies the row — but kept alongside it so a row can be
  -- attributed, audited, or revoked by principal without decrypting the
  -- tokens first.
  sub text NOT NULL,

  -- AES-256-GCM ciphertext, laid out as iv || tag || ciphertext. The
  -- application encrypts before insert and decrypts after select; nothing in
  -- this schema or any query against it ever sees the plaintext access
  -- token. The encryption key is separate from SESSION_ENCRYPT_KEY, so a
  -- compromise of one does not open the other.
  access_token bytea NOT NULL,

  -- Expiry of the access token above, mirroring what Zitadel returned at
  -- issue or refresh time. Read before every platform-API call so an
  -- about-to-expire token can be refreshed proactively rather than failing
  -- the request it was meant to authorize.
  access_expires_at timestamptz NOT NULL,

  -- AES-256-GCM ciphertext, same iv || tag || ciphertext layout as
  -- access_token, encrypted under the same key. Nullable: a session can lose
  -- its refresh token (Zitadel rotates refresh tokens on use, and the
  -- console does not always have a response to persist the new one on) and
  -- carry on until access_expires_at, at which point the platform API
  -- becomes unreachable for that session rather than the whole login
  -- failing — the same degrade-not-break trade Step 1 made explicit.
  refresh_token bytea,

  -- Expiry of the session itself, mirroring the cookie's own `exp` claim.
  -- Not derived from either token's expiry — a refresh token can outlive or
  -- fall short of the session lifetime the cookie promises. Exists solely so
  -- rows can be pruned once the session they belong to could not possibly be
  -- presented again; nothing here is enforced by this table itself, since
  -- expiry enforcement of the session happens where the cookie is verified.
  session_expires_at timestamptz NOT NULL,

  -- Last time this row's tokens changed, set by the application on every
  -- insert and every refresh-triggered update. No behavior in this table
  -- depends on it; it exists for the same operational visibility every other
  -- mutable row in this schema carries.
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Supports the prune sweep: find every row whose session could not possibly
-- be presented again. Not implemented here, for the same reason 0018 and
-- 0028 give for their own retention statements — it is one scheduled
-- statement against this index and needs no schema change, so it can be
-- added when the module that writes this table ships rather than guessed at
-- now.
--
--   DELETE FROM operator_api_tokens WHERE session_expires_at < now()
CREATE INDEX operator_api_tokens_session_expires_idx
  ON operator_api_tokens (session_expires_at);

COMMIT;
